<a href="https://colab.research.google.com/github/mcondemaita/python_projects/blob/main/Relational_databases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Relational Database Management Systems

*   PostgreSQL
*   MySQL
*   SQLite: fast & simple
*   SQL = Structured Query Language

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///Northwind.sqlite') #idk the path
table_names = engine.table_names() #['Categories', 'Customers', 'EmployeeTerritories"] get a list of the names

In [ ]:
#Query data
# SELECT * FORM table_Name on sql but in python
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine('sqlite:///Northwind.sqlite') #idk the path
# Open engine connection:
connect = engine.connect()
# Perform query:
request = connect.execute('SELECT * FROM Orders')
# Save results of the query to DataFrame: df
df = pd.DataFrame(request.fetchall())
#or df = pd.DataFrame(reguest.fetchall(size =5)) side on rows
#fix colum names
df.columns = connect.keys()
connect.close()

In [ ]:
#Using Context Manager

from sqlalchemy import create_engine
import pandas as pd
engine = create_engine('sqlite:///Northwind.sqlite') #idk the path

with engine.connect() as con:
  request = con.execute('SELECT Order ID', 'OrderDate FROM TABLE_NAME WHERE COL >=6')
  df1 = pd.DataFrame(request.fetchmany(size=5))
  df1.columns = request.keys()
  con.close()

## Pandas way to query

In [ ]:
df.read_sql_query('Select * from Orders', engine)

# Confirm that both methods yield the same result
df.equals(df1)
# output True or Flase

In [ ]:
#inner join table python
df = pd.read_sql_query('SELECT OrderID, CompanyName FROM Orders INNER JOIN Customers on Order.CustomerID = Customers.CustomerID WHERE ', engine)

#Importing Flat files form the web


*   urllib package, provides interface for fetching data across the web
    urlopen() - accepts URLs instead of file names
*

In [6]:
 # Import package
from urllib.request import urlretrieve
import pandas as pd
 # Assign url of file: url
url = 'https://assets.datacamp.com/production/course_1606/datasets/winequality-red.csv'
 # Save file locally this is optional if dont want to save just go to read file
urlretrieve(url, 'winequality_white.csv')
# Read file into a DataFrame and print its head
df = pd.read_csv('winequality_white.csv', sep=';')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5